<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Anh-IT-ngheo-2.local" failures="14" tests="14" name="Surefire test" time="7.78" errors="0" timestamp="2024-02-02T00:27:36 ICT">
  <testcase classname="Tests.DeckTest" name="shuffleDeck" time="0.945">
    <failure type="io.restassured.module.jsv.JsonSchemaValidationException" message="java.io.FileNotFoundException: src/test/resources/shuffe_card_schema.json (No such file or directory)">
      <![CDATA[io.restassured.module.jsv.JsonSchemaValidationException: java.io.FileNotFoundException: src/test/resources/shuffe_card_schema.json (No such file or directory)
at io.restassured.module.jsv.JsonSchemaValidator$JsonSchemaValidatorFactory.create(JsonSchemaValidator.java:286)
at io.restassured.module.jsv.JsonSchemaValidator.matchesJsonSchema(JsonSchemaValidator.java:157)
at Tests.DeckTest.shuffleDeck(DeckTest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.io.FileNotFoundException: src/test/resources/shuffe_card_schema.json (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
at com.github.fge.jackson.JsonLoader.fromFile(JsonLoader.java:160)
at io.restassured.module.jsv.JsonSchemaValidator$3.createSchemaInstance(JsonSchemaValidator.java:155)
at io.restassured.module.jsv.JsonSchemaValidator$3.createSchemaInstance(JsonSchemaValidator.java:152)
at io.restassured.module.jsv.JsonSchemaValidator$JsonSchemaValidatorFactory.create(JsonSchemaValidator.java:284)
... 33 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- shuffleDeck -->
  <testcase classname="Tests.ProductLineTest" name="createProductLine" time="1.937">
    <failure type="java.lang.AssertionError" message="expected [201] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [401]
at Tests.ProductLineTest.createProductLine(ProductLineTest.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- createProductLine -->
  <testcase classname="Tests.ProductLineTest" name="deleteProductLine" time="0.154">
    <failure type="java.lang.AssertionError" message="expected [201] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [401]
at Tests.ProductLineTest.deleteProductLine(ProductLineTest.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- deleteProductLine -->
  <testcase classname="Tests.ProductLineTest" name="getListProductLineDefault" time="0.24">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at Tests.ProductLineTest.getListProductLineDefault(ProductLineTest.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- getListProductLineDefault -->
  <testcase classname="Tests.ProductLineTest" name="updateProductLine" time="0.209">
    <failure type="java.lang.AssertionError" message="expected [201] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [401]
at Tests.ProductLineTest.updateProductLine(ProductLineTest.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- updateProductLine -->
  <testcase classname="Tests.BrandTest" name="createBrand" time="0.16">
    <failure type="java.lang.AssertionError" message="expected [201] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [401]
at Tests.BrandTest.createBrand(BrandTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- createBrand -->
  <testcase classname="Tests.BrandTest" name="deleteBrand" time="0.173">
    <failure type="java.lang.AssertionError" message="expected [201] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [401]
at Tests.BrandTest.deleteBrand(BrandTest.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- deleteBrand -->
  <testcase classname="Tests.BrandTest" name="getListBrandDefault" time="0.155">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at Tests.BrandTest.getListBrandDefault(BrandTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- getListBrandDefault -->
  <testcase classname="Tests.BrandTest" name="updateBrand" time="0.167">
    <failure type="java.lang.AssertionError" message="expected [201] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [401]
at Tests.BrandTest.updateBrand(BrandTest.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- updateBrand -->
  <testcase classname="Tests.ModelTest" name="createModel" time="0.465">
    <failure type="java.lang.AssertionError" message="expected [201] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [401]
at Tests.ModelTest.createModel(ModelTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- createModel -->
  <testcase classname="Tests.ModelTest" name="deleteModel" time="1.566">
    <failure type="java.lang.AssertionError" message="expected [201] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [401]
at Tests.ModelTest.deleteModel(ModelTest.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- deleteModel -->
  <testcase classname="Tests.ModelTest" name="getListModelDefault" time="0.767">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at Tests.ModelTest.getListModelDefault(ModelTest.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- getListModelDefault -->
  <testcase classname="Tests.ModelTest" name="updateModel" time="0.299">
    <failure type="java.lang.AssertionError" message="expected [201] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [401]
at Tests.ModelTest.updateModel(ModelTest.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- updateModel -->
  <testcase classname="Tests.CardsTest" name="partialDeck" time="0.362">
    <failure type="java.lang.NoSuchMethodError" message="&amp;apos;void org.hamcrest.Matcher.describeMismatch(java.lang.Object, org.hamcrest.Description)&amp;apos;">
      <![CDATA[java.lang.NoSuchMethodError: 'void org.hamcrest.Matcher.describeMismatch(java.lang.Object, org.hamcrest.Description)'
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at Tests.CardsTest.partialDeck(CardsTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- partialDeck -->
</testsuite> <!-- Surefire test -->
